import {
  MeetingItem,
  MeetingStats,
  MeetingInsights,
  MeetingAttendee,
} from "@/types/meetings";

// Placeholder stubs — meetings are not yet connected to real people data
const EMPTY_PERSON = { id: "", user_id: "", full_name: "", email: "", job_title: null };
const pTashin = EMPTY_PERSON;
const pSarah = EMPTY_PERSON;
const pRahim = EMPTY_PERSON;
const pArafath = EMPTY_PERSON;
const pFatema = EMPTY_PERSON;
const pTanjir = EMPTY_PERSON;

function makeAttendees(people: typeof EMPTY_PERSON[]): MeetingAttendee[] {
  return people.map((p) => ({
    id: `att-${p.id}`,
    user_id: p.user_id,
    full_name: p.full_name ?? "",
    email: p.email ?? "",
    avatar_url: null,
    role: p.job_title ?? undefined,
    rsvp: "Accepted" as const,
  }));
}

export const DEFAULT_MEETING_STATS: MeetingStats = {
  totalMeetings: 156,
  upcomingThisWeek: 12,
  totalAttended: 124,
  totalHours: 86.4,
  cancelledThisMonth: 8,
};

export const DEFAULT_MEETING_INSIGHTS: MeetingInsights = {
  meetingsHeld: 28,
  totalParticipants: 156,
  avgMeetingMinutes: 54,
  meetingsCancelled: 8,
};

export const DEFAULT_MEETINGS_DATA: MeetingItem[] = [
  {
    id: "meet-001",
    workspace_id: "ws-default",
    title: "Weekly Development Standup",
    description: "Sprint progress, blockers and updates",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-21",
    start_time: "10:00 AM",
    end_time: "10:30 AM",
    duration_minutes: 30,
    timezone: "Asia/Dhaka",
    organizer_id: "u-tashin",
    organizer_name: "Tashin Khan",
    organizer_role: "Development Lead",
    organizer_avatar: null,
    department_id: "dept-dev",
    department_name: "Development",
    attendees: makeAttendees([pSarah, pRahim, pArafath, pFatema, pTanjir]),
    attendee_count: 11,
    agenda: [
      { id: "ag-1", order: 1, title: "Review sprint board status", duration_minutes: 10 },
      { id: "ag-2", order: 2, title: "Share blockers and dependencies", duration_minutes: 10 },
      { id: "ag-3", order: 3, title: "Assign next priorities", duration_minutes: 10 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/dev-standup",
    meeting_id_code: "382-947-615",
    is_recurring: true,
    recurrence: "Weekly",
    notify_attendees: true,
    created_at: "2026-08-01T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-002",
    workspace_id: "ws-default",
    title: "Client Project Kickoff",
    description: "Project overview and expectations",
    type: "Client",
    status: "Upcoming",
    date: "2026-05-21",
    start_time: "2:00 PM",
    end_time: "3:00 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-sarah",
    organizer_name: "Sarah Ahmed",
    organizer_role: "Project Manager",
    organizer_avatar: null,
    department_id: "dept-design",
    department_name: "Design",
    attendees: makeAttendees([pTashin, pArafath, pFatema]),
    attendee_count: 7,
    agenda: [
      { id: "ag-4", order: 1, title: "Introductions and team overview", duration_minutes: 10 },
      { id: "ag-5", order: 2, title: "Project scope and deliverables", duration_minutes: 25 },
      { id: "ag-6", order: 3, title: "Timeline and milestone planning", duration_minutes: 25 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/client-kickoff",
    meeting_id_code: "614-203-891",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-10T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-003",
    workspace_id: "ws-default",
    title: "Q3 Budget Planning",
    description: "Budget review and allocation",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-22",
    start_time: "11:00 AM",
    end_time: "12:30 PM",
    duration_minutes: 90,
    timezone: "Asia/Dhaka",
    organizer_id: "u-arafath",
    organizer_name: "Arafath Hossain",
    organizer_role: "Finance Manager",
    organizer_avatar: null,
    department_id: "dept-ops",
    department_name: "Operations",
    attendees: makeAttendees([pTashin, pSarah, pTanjir, pFatema]),
    attendee_count: 8,
    agenda: [
      { id: "ag-7", order: 1, title: "Q2 budget variance review", duration_minutes: 30 },
      { id: "ag-8", order: 2, title: "Q3 allocation proposals", duration_minutes: 35 },
      { id: "ag-9", order: 3, title: "Approval and sign-off", duration_minutes: 25 },
    ],
    attachments: [],
    location_type: "Physical",
    location_value: "Conference Room A, Floor 3",
    meeting_id_code: "739-581-024",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-12T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-004",
    workspace_id: "ws-default",
    title: "Marketing Strategy Meeting",
    description: "Campaigns, content and growth",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-23",
    start_time: "3:00 PM",
    end_time: "4:00 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-fatema",
    organizer_name: "Fatema Islam",
    organizer_role: "Marketing Lead",
    organizer_avatar: null,
    department_id: "dept-design",
    department_name: "Design",
    attendees: makeAttendees([pTashin, pSarah, pRahim, pTanjir, pArafath]),
    attendee_count: 9,
    agenda: [
      { id: "ag-10", order: 1, title: "Campaign performance review", duration_minutes: 20 },
      { id: "ag-11", order: 2, title: "Content calendar planning", duration_minutes: 20 },
      { id: "ag-12", order: 3, title: "Growth experiments and OKRs", duration_minutes: 20 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/marketing-strategy",
    meeting_id_code: "201-467-358",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-14T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-005",
    workspace_id: "ws-default",
    title: "Product Roadmap Review",
    description: "Q3 roadmap and feature planning",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-24",
    start_time: "10:30 AM",
    end_time: "12:00 PM",
    duration_minutes: 90,
    timezone: "Asia/Dhaka",
    organizer_id: "u-tanjir",
    organizer_name: "Munshi Tanjir",
    organizer_role: "Product Manager",
    organizer_avatar: null,
    department_id: "dept-ops",
    department_name: "Operations",
    attendees: makeAttendees([pTashin, pSarah, pRahim, pArafath, pFatema]),
    attendee_count: 12,
    agenda: [
      { id: "ag-13", order: 1, title: "Review Q2 roadmap delivery", duration_minutes: 30 },
      { id: "ag-14", order: 2, title: "Q3 feature prioritization", duration_minutes: 35 },
      { id: "ag-15", order: 3, title: "Design and dev alignment", duration_minutes: 25 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/product-roadmap",
    meeting_id_code: "563-829-047",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-15T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-006",
    workspace_id: "ws-default",
    title: "HR Policy Review Meeting",
    description: "Review company HR policies",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-25",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-sarah",
    organizer_name: "Sarah Ahmed",
    organizer_role: "HR Manager",
    organizer_avatar: null,
    department_id: "dept-design",
    department_name: "Design",
    attendees: makeAttendees([pTashin, pFatema, pTanjir]),
    attendee_count: 7,
    agenda: [
      { id: "ag-16", order: 1, title: "Policy updates Q3", duration_minutes: 20 },
      { id: "ag-17", order: 2, title: "Leave policy amendments", duration_minutes: 20 },
      { id: "ag-18", order: 3, title: "Remote work guidelines", duration_minutes: 20 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/hr-policy",
    meeting_id_code: "174-936-802",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-16T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-007",
    workspace_id: "ws-default",
    title: "Vendor Evaluation Meeting",
    description: "Review vendor proposals",
    type: "Client",
    status: "Upcoming",
    date: "2026-05-26",
    start_time: "2:30 PM",
    end_time: "3:30 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-arafath",
    organizer_name: "Arafath Hossain",
    organizer_role: "Procurement Lead",
    organizer_avatar: null,
    department_id: "dept-ops",
    department_name: "Operations",
    attendees: makeAttendees([pTashin, pTanjir]),
    attendee_count: 6,
    agenda: [
      { id: "ag-19", order: 1, title: "Vendor proposal presentations", duration_minutes: 30 },
      { id: "ag-20", order: 2, title: "Comparison and scoring", duration_minutes: 20 },
      { id: "ag-21", order: 3, title: "Decision and next steps", duration_minutes: 10 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/vendor-eval",
    meeting_id_code: "408-715-263",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-17T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-008",
    workspace_id: "ws-default",
    title: "New Hire Orientation",
    description: "Welcome and onboarding session",
    type: "Internal",
    status: "Upcoming",
    date: "2026-05-27",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-fatema",
    organizer_name: "Fatema Islam",
    organizer_role: "HR Specialist",
    organizer_avatar: null,
    department_id: "dept-design",
    department_name: "Design",
    attendees: makeAttendees([pTashin, pSarah, pRahim, pArafath, pTanjir]),
    attendee_count: 15,
    agenda: [
      { id: "ag-22", order: 1, title: "Company overview and culture", duration_minutes: 20 },
      { id: "ag-23", order: 2, title: "Tools, access, and systems", duration_minutes: 20 },
      { id: "ag-24", order: 3, title: "Team introductions", duration_minutes: 20 },
    ],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/orientation",
    meeting_id_code: "951-384-670",
    is_recurring: false,
    notify_attendees: true,
    created_at: "2026-08-18T09:00:00Z",
    updated_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "meet-009",
    workspace_id: "ws-default",
    title: "Q2 Performance Review",
    description: "Annual review and feedback session",
    type: "Internal",
    status: "Completed",
    date: "2026-05-14",
    start_time: "10:00 AM",
    end_time: "11:00 AM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-tashin",
    organizer_name: "Tashin Khan",
    organizer_role: "Development Lead",
    organizer_avatar: null,
    attendees: makeAttendees([pSarah, pArafath]),
    attendee_count: 6,
    agenda: [],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/q2-review",
    meeting_id_code: "100-200-300",
    is_recurring: false,
    notify_attendees: false,
    created_at: "2026-08-01T09:00:00Z",
    updated_at: "2026-08-14T12:00:00Z",
  },
  {
    id: "meet-010",
    workspace_id: "ws-default",
    title: "Design System Workshop",
    description: "Component library and token review",
    type: "Internal",
    status: "Completed",
    date: "2026-05-15",
    start_time: "2:00 PM",
    end_time: "3:30 PM",
    duration_minutes: 90,
    timezone: "Asia/Dhaka",
    organizer_id: "u-sarah",
    organizer_name: "Sarah Ahmed",
    organizer_role: "Design Lead",
    organizer_avatar: null,
    attendees: makeAttendees([pTashin, pFatema, pArafath]),
    attendee_count: 8,
    agenda: [],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/design-workshop",
    meeting_id_code: "500-600-700",
    is_recurring: false,
    notify_attendees: false,
    created_at: "2026-08-05T09:00:00Z",
    updated_at: "2026-08-15T16:00:00Z",
  },
  {
    id: "meet-011",
    workspace_id: "ws-default",
    title: "API Integration Planning",
    description: "Third-party integrations roadmap",
    type: "Internal",
    status: "Cancelled",
    date: "2026-05-18",
    start_time: "3:00 PM",
    end_time: "4:00 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-arafath",
    organizer_name: "Arafath Hossain",
    organizer_role: "Developer",
    organizer_avatar: null,
    attendees: makeAttendees([pTashin, pSarah]),
    attendee_count: 4,
    agenda: [],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/api-planning",
    meeting_id_code: "800-900-100",
    is_recurring: false,
    notify_attendees: false,
    cancelled_at: "2026-08-18T10:00:00Z",
    cancellation_reason: "Scheduling conflict — rescheduled to next week",
    created_at: "2026-08-10T09:00:00Z",
    updated_at: "2026-08-18T10:00:00Z",
  },
  {
    id: "meet-012",
    workspace_id: "ws-default",
    title: "Investor Sync",
    description: "Quarterly investor update call",
    type: "Client",
    status: "Cancelled",
    date: "2026-05-19",
    start_time: "11:00 AM",
    end_time: "12:00 PM",
    duration_minutes: 60,
    timezone: "Asia/Dhaka",
    organizer_id: "u-tashin",
    organizer_name: "Tashin Khan",
    organizer_role: "Development Lead",
    organizer_avatar: null,
    attendees: makeAttendees([pSarah, pTanjir]),
    attendee_count: 5,
    agenda: [],
    attachments: [],
    location_type: "Video",
    meeting_link: "https://meet.brnnd.com/investor-sync",
    meeting_id_code: "300-400-500",
    is_recurring: false,
    notify_attendees: false,
    cancelled_at: "2026-08-17T14:00:00Z",
    cancellation_reason: "Investor unavailable — rescheduled to Q3 update",
    created_at: "2026-08-08T09:00:00Z",
    updated_at: "2026-08-17T14:00:00Z",
  },
];

export function getMeetingById(id: string): MeetingItem | undefined {
  return DEFAULT_MEETINGS_DATA.find((m) => m.id === id);
}

export function getMeetingsByStatus(status: "Upcoming" | "Past" | "Cancelled"): MeetingItem[] {
  if (status === "Upcoming") {
    return DEFAULT_MEETINGS_DATA.filter((m) => m.status === "Upcoming" || m.status === "Live");
  }
  if (status === "Past") {
    return DEFAULT_MEETINGS_DATA.filter((m) => m.status === "Completed");
  }
  return DEFAULT_MEETINGS_DATA.filter((m) => m.status === "Cancelled");
}

export function getMeetingsForDate(date: string): MeetingItem[] {
  return DEFAULT_MEETINGS_DATA.filter(
    (m) => m.date === date && (m.status === "Upcoming" || m.status === "Live")
  );
}

export type { MeetingInsights, MeetingStats };
